---

actAs: 
    Timestampable: 

Administrasi_Model_User:
    tableName: user
    columns:
        username: 
            type: string(30)
            unique: true
            notnull: true
        password: 
            type: string(100)
            notnull: true
        role:
            type: string(20)
            notnull: true
            default: "guest"
        isactive:
            type: boolean
            default: false
        catatan:
            type: sring(255)