<? if($this->user): ?>
    <fieldset>
        <input id="qsearch" name="qsearch" placeholder="Filter.." />
    </fieldset>
    <table id="table-user" class="table table-bordered table-condensed table-striped">
        <thead>
            <tr>
                <th>No</th>
                <th>Username</th>
                <th>Role</th>
                
            </tr>
        </thead>
        <tbody>
            <? foreach($this->user as $k => $v): ?>
            <tr>
                <td><?= ($k + 1) ?></td>
                <td class="editable" id="<?= $v->id ?>-username-unique"><?= $v->username ?></td>
                <td class="editable" id="<?= $v->id ?>-role-etd"><?= $v->role ?></td>
                
            </tr>
            <? endforeach ?>
        </tbody>
    </tabl>
<? endif ?>

<script type="text/javascript">
//<!--[CDATA[
$(function(){
    $('#qsearch').quicksearch('#table-user tbody tr');
    
})
//]]    
</script>