<?= $this->form ? $this->form : '' ?>

<script type="text/javascript">
//<!-[CDATA[
$(function(){
    $('#form-input-user').validate({
        submitHandler: function(form){
            $(form).ajaxSubmit({
                success: function(data){
                    
                }
            });
        }
    });
    $('#username').on('change', function(){
        $.ajax({
            type: 'post',
            data: 'tbl=user&fld=username&val=' + $('#username').val(),
            url: '/administrasi/index/xhr/do/isunique/format/html',
            success: function(json){
                var obj = $.parseJSON(json);
                if(obj.alert){
                    $('#password, #confirm, #submit').attr('disabled', 'disabled');
                    $('#username').focus();
                }else{
                    $('#password, #confirm, #submit').removeAttr('disabled');
                }
            }
        })
    })
})
//]]>
</script>