<?php

/**
 * Administrasi_Model_Base_Big
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nip
 * @property string $nama
 * @property string $kode
 * @property sring $catatan
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Administrasi_Model_Base_Big extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('big');
        $this->hasColumn('nip', 'integer', 20, array(
             'type' => 'integer',
             'unique' => true,
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('nama', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('kode', 'string', 2, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '2',
             ));
        $this->hasColumn('catatan', 'sring', 255, array(
             'type' => 'sring',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}