<?php

/**
 * Administrasi_Model_Base_Bik
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nik
 * @property string $nama
 * @property enum $jk
 * @property string $tugas
 * @property sring $catatan
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Administrasi_Model_Base_Bik extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bik');
        $this->hasColumn('nik', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             'length' => '10',
             ));
        $this->hasColumn('nama', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('jk', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'L',
              1 => 'P',
             ),
             ));
        $this->hasColumn('tugas', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('catatan', 'sring', 255, array(
             'type' => 'sring',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}