<?php

/**
 * Administrasi_Model_Base_Semester
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $kode
 * @property string $tahun_ajaran
 * @property enum $semester
 * @property date $awal_ajaran
 * @property date $akhir_ajaran
 * @property string $catatan
 * @property Doctrine_Collection $Administrasi_Model_StatusSiswa
 * @property Doctrine_Collection $Administrasi_Model_PrestasiSiswa
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Administrasi_Model_Base_Semester extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('semester');
        $this->hasColumn('id', 'integer', 3, array(
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '3',
             ));
        $this->hasColumn('kode', 'string', 15, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '15',
             ));
        $this->hasColumn('tahun_ajaran', 'string', 9, array(
             'type' => 'string',
             'primary' => true,
             'length' => '9',
             ));
        $this->hasColumn('semester', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'gasal',
              1 => 'genap',
             ),
             ));
        $this->hasColumn('awal_ajaran', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('akhir_ajaran', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('catatan', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Administrasi_Model_StatusSiswa', array(
             'local' => 'kode',
             'foreign' => 'kode_semester'));

        $this->hasMany('Administrasi_Model_PrestasiSiswa', array(
             'local' => 'kode',
             'foreign' => 'kode_semester'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}