<div class="container">
    <div id="slideshow">
        <div>
            A human being is not attaining his full heights until he is educated. 
            <strong>Horace Mann</strong>
        </div>

        <div>
            A liberal education is at the heart of a civil society, and at the heart of a liberal education is the act of teaching. 
            <strong>A. Bartlett Giamatti</strong>
        </div>
        <div>
            America is becoming so educated that ignorance will be a novelty. 
            I will belong to the select few. 
            <strong>Will Rogers</strong>
        </div>

        <div>
            America is the best half-educated country in the world. 
            <strong>Nicholas M. Butler </strong>
        </div>

        <div>
            An educated man is thoroughly inoculated against humbug, thinks for himself and tries to give his thoughts, in speech or on paper, some style. 
            <strong>Alan K. Simpson</strong>
        </div>

        <div>
            An educated people can be easily governed. 
            <strong>Frederick The Great </strong>
        </div>

        <div>
            An educated person is one who has learned that information almost always turns out to be at best incomplete and very often false, misleading, fictitious, mendacious - just dead wrong. 
            <strong>Russell Baker </strong>
        </div>

        <div>
            An education isn't how much you have committed to memory, or even how much you know. It's being able to differentiate between what you know and what you don't. 
            <strong>Anatole France </strong>
        </div>

        <div>
            Children have to be educated, but they have also to be left to educate themselves. 
            <strong>Ernest Dimnet </strong>
        </div>

        <div>
            Data is not information, information is not knowledge, knowledge is not understanding, understanding is not wisdom. 
            <strong>Clifford Stoll</strong>
        </div> 

        <div>
            Develop a passion for learning. If you do, you will never cease to grow. 
            <strong>Anthony J. D'Angelo </strong>
        </div>

        <div>
            Education is a better safeguard of liberty than a standing army. 
            <strong>Edward Everett </strong>
        </div>

        <div>
            Education is a progressive discovery of our own ignorance. 
            <strong>Will Durant </strong>
        </div>

        <div>
            Education is all a matter of building bridges. 
            <strong>Ralph Ellison </strong>
        </div>

        <div>
            Education is an admirable thing, but it is well to remember from time to time that nothing that is worth knowing can be taught. 
            <strong>Oscar Wilde </strong>
        </div>

        <div>
            Education is learning what you didn't even know you didn't know. 
            <strong>Daniel J. Boorstin </strong>
        </div>

        <div>
            Education is not preparation for life; education is life itself. 
            <strong>John Dewey </strong>
        </div>

        <div>
            Education is not the filling of a pail, but the lighting of a fire. 
            <strong>William Butler Yeats </strong>
        </div>

        <div>
            Education is simply the soul of a society as it passes from one generation to another. 
            <strong>Gilbert K. Chesterton </strong>
        </div>

        <div>
            Education is the ability to listen to almost anything without losing your temper or your self-confidence. 
            <strong>Robert Frost </strong>
        </div>

        <div>
            Education is the key to unlock the golden door of freedom.
            <strong>George Washington Carver</strong>
        </div>

        <div>
            Education is the transmission of civilization.
            <strong>Will Durant</strong>
        </div>

        <div>
            Education is what survives when what has been learned has been forgotten.
            <strong>B. F. Skinner</strong>
        </div>

        <div>
            Education, n.: That which discloses to the wise and disguises from the foolish their lack of understanding.
            <strong>Ambrose Bierce</strong>
        </div>

        <div>
            Education... has produced a vast population able to read but unable to distinguish what is worth reading.
            <strong>G. M. Trevelyan</strong>
        </div>

        <div>
            Education's purpose is to replace an empty mind with an open one.
            <strong>Malcolm Forbes</strong>
        </div>

        <div>
            Every educated person is a future enemy.
            <strong>Martin Bormann</strong>
        </div>

        <div>
            Good teaching is one-fourth preparation and three-fourths pure theatre.
            <strong>Gail Godwin</strong>
        </div>

        <div>
            He who opens a school door, closes a prison.
            <strong>Victor Hugo</strong>
        </div>

        <div>
            I know a lot of people think I'm dumb. Well, at least I ain't no educated fool.
            <strong>Leon Spinks</strong>
        </div>

        <div>
            I prefer the company of peasants because they have not been educated sufficiently to reason incorrectly.
            <strong>Michel de Montaigne</strong>
        </div>


        
        <div>
            I think everyone should go to college and get a degree and then spend six months as a bartender and six months as a cabdriver. Then they would really be educated.
            <strong>Al McGuire</strong>
        </div>

        <div>
            I would like to learn, or remember, how to live.
            <strong>Annie Dillard</strong>
        </div>

        <div>
            I would rather entertain and hope that people learned something than educate people and hope they were entertained.
            <strong>Walt Disney</strong>
        </div>
        <div>
            I'm not afraid of storms, for I'm learning to sail my ship.
            <strong>Aeschylus</strong>
        </div>
        <div>
            If an ignorant person is attracted by the things of the world, that is bad. But if a learned person is thus attracted, it is worse.
            <strong>Abu Bakr</strong>
        </div>
        <div>
            If I had learned education I would not have had time to learn anything else.
        </div>
        <div>
            If the Romans had been obliged to learn Latin, they would never have found time to conquer the world.
            <strong>Heinrich Heine</strong>
        </div>

    </div>
</div>

<? $this->headStyle()->captureStart() ?>
#slideshow { 
    margin: 50px auto; 
    position: relative; 
    width: 240px; 
    height: 240px; 
    padding: 10px; 
    box-shadow: 0 0 20px rgba(0,0,0,0.4); 
}

#slideshow > div { 
    position: absolute; 
    top: 10px; 
    left: 10px; 
    right: 10px; 
    bottom: 10px; 
}
<? $this->headStyle()->captureEnd() ?>

<? $this->headScript()->captureStart() ?>
$(function(){
   $("#slideshow > div:gt(0)").hide();

    setInterval(function() { 
      $('#slideshow > div:first')
        .fadeOut(1000)
        .next()
        .fadeIn(1000)
        .end()
        .appendTo('#slideshow');
    },  3000); 
})
<? $this->headScript()->captureEnd() ?>