<div class="container">
    <div class="span2">
        <div class="accordion" id="guru">
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" 
                        data-parent="#guru" data-target="#siswa">Siswa</a>
                </div>
                <div id="siswa" class="accordion-body collapse in">
                    <div class="accordion-inner">
                            --- siswa--
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="span9" id="ajax-content">

    </div>
</div>